import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getSignInUrl, withAuth } from "@workos-inc/authkit-nextjs";
import "./globals.css";
import Header from './components/Header';
import Footer from './components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog Platform",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await withAuth(); // Get the user data from WorkOS Auth
  const signInUrl = await getSignInUrl(); // Get the sign-in URL

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main>
          <Header user={user} signInUrl={signInUrl} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
